#!/usr/bin/env python3

from subprocess import Popen, DEVNULL, PIPE
from time import localtime, strftime

import argparse


cq_cmd = ["condor_q", "-af:Vj", "JobStatus", "CMD", "Qdate", "JobStartDate", "JobLastStartDate", "JobCurrentStartDate"]

cq_fmt = "{0:10} {1:5} {2:20} {3}"

st_fmt = "\nJobs total: {total}, compl: {compl}, del: {deleted}, idle: {idle}, run: {run}, hold: {hold}"

stc2str = {0:"unexp", 1:"idle", 2:"run", 3:"del", 4:"compl", 5:"hold", 6:"error"}

timeval_hdg = {0:"Queue Time", 1:"Start Time", 2:"Last Start Time", 3:"Current Start Time"}


def tse2timestr(tse):
    if tse == b'undefined':
        return "n/a"
    else:
        return strftime("%Y-%m-%d %H:%M:%S", localtime(int(tse)))


def update_statistics(jstatus, stats):
    if   jstatus == 1: stats['idle'] += 1
    elif jstatus == 2: stats['run'] += 1
    elif jstatus == 3: stats['deleted'] += 1
    elif jstatus == 4: stats['compl'] += 1
    elif jstatus == 5: stats['hold'] += 1
    else: pass
    stats['total'] += 1


def process_input_line(line, stats, args):
    update_statistics(int(line[1]), stats)
    if int(line[1]) in args.jst_mask:
        print(cq_fmt.format(line[0].decode('utf-8'),
                            stc2str[int(line[1])],
                            tse2timestr(line[3 + args.timeval]),
                            line[2].decode('utf-8').strip('"')))


def parse_cmdline():
    ap = argparse.ArgumentParser(description="condor_qc: Output re-formatting wrapper for condor_q(1)")
    ap.add_argument("-s", "--stats", action="store_true", help="Print statistics")
    ap.add_argument("-I", "--idle", action="store_true", help="Filter idle jobs")
    ap.add_argument("-R", "--run", action="store_true", help="Filter running jobs")
    ap.add_argument("-H", "--hold", action="store_true", help="Filter held jobs")
    ap.add_argument("--qtime", action="store_true", help="Print job queue time")
    ap.add_argument("--stime", action="store_true", help="Print job start time (default)")
    ap.add_argument("--ltime", action="store_true", help="Print job last start time")
    ap.add_argument("--ctime", action="store_true", help="Print job current start time")
    return ap.parse_args()


def update_args(args):
    if args.idle or args.run or args.hold:
        args.jst_mask = set()
    else:
        args.jst_mask = {0, 1, 2, 3, 4, 5, 6}
    if args.idle: args.jst_mask.add(1)
    if args.run:  args.jst_mask.add(2)
    if args.hold: args.jst_mask.add(5)

    if   args.qtime: args.timeval = 0
    elif args.stime: args.timeval = 1
    elif args.ltime: args.timeval = 2
    elif args.ctime: args.timeval = 3
    else:            args.timeval = 1    # start time is default
    return args


def main():
    args = update_args(parse_cmdline())
    stats = dict(total=0, compl=0, deleted=0, idle=0, run=0, hold=0)
    headers = ["JobID", "ST"] + [timeval_hdg[args.timeval]] + ["CMD"]
    try:
        print(cq_fmt.format(*headers))
        with Popen(cq_cmd, stdin=DEVNULL, stdout=PIPE) as subp:
            for line in subp.stdout:
                process_input_line(line.split(), stats, args)
        if args.stats:
            print(st_fmt.format(**stats))
    except BrokenPipeError:
        # broken pipe happens all the time when piped to less(1), just ignore
        pass


if __name__ == "__main__":
    main()
