#!/usr/bin/env python3

from subprocess import Popen, DEVNULL, PIPE
from time import localtime, strftime

import argparse


cq_cmd = ["condor_q", "-af:Vj", "JobStatus", "CMD", "Qdate", "JobStartDate", "JobLastStartDate", "JobCurrentStartDate"]

cq_fmt = "{0:10} {1:5} {2:20} {3}"

st_fmt = "\nJobs total: {total}, compl: {compl}, del: {deleted}, idle: {idle}, run: {run}, hold: {hold}"

stc2str = {0:"unexp", 1:"idle", 2:"run", 3:"del", 4:"compl", 5:"hold", 6:"error"}

timeval_hdg = {0:"Queue Time", 1:"Start Time", 2:"Last Start Time", 3:"Current Start Time"}


def tse2timestr(tse):
    if tse == b'undefined':
        return "n/a"
    else:
        return strftime("%Y-%m-%d %H:%M:%S", localtime(int(tse)))


def update_statistics(jstatus, stats):
    if   jstatus == 1: stats['idle'] += 1
    elif jstatus == 2: stats['run'] += 1
    elif jstatus == 3: stats['deleted'] += 1
    elif jstatus == 4: stats['compl'] += 1
    elif jstatus == 5: stats['hold'] += 1
    else: pass
    stats['total'] += 1


def process_input_line(line, stats, timeval):
    update_statistics(int(line[1]), stats)
    print(cq_fmt.format(line[0].decode('utf-8'),
                        stc2str[int(line[1])],
                        tse2timestr(line[3 + timeval]),
                        line[2].decode('utf-8').strip('"')))


def parse_cmdline():
    ap = argparse.ArgumentParser(description="condor_qc: Output re-formatting wrapper for condor_q(1)")
    ap.add_argument("-s", "--stats", action="store_true", help="Print statistics")
    ap.add_argument("--qtime", action="store_true", help="Print job queue time")
    ap.add_argument("--stime", action="store_true", help="Print job start time")
    ap.add_argument("--ltime", action="store_true", help="Print job last start time")
    ap.add_argument("--ctime", action="store_true", help="Print job current start time")
    return ap.parse_args()


def time_to_display(args):
    if args.qtime:
        return 0
    elif args.stime:
        return 1
    elif args.ltime:
        return 2
    elif args.ctime:
        return 3
    else:
        return 1    # start time is default


def main():
    args = parse_cmdline()
    stats = dict(total=0, compl=0, deleted=0, idle=0, run=0, hold=0)
    timeval = time_to_display(args)
    headers = ["JobID", "ST"] + [timeval_hdg[timeval]] + ["CMD"]
    try:
        print(cq_fmt.format(*headers))
        with Popen(cq_cmd, stdin=DEVNULL, stdout=PIPE) as subp:
            for line in subp.stdout:
                process_input_line(line.split(), stats, timeval)
        if args.stats:
            print(st_fmt.format(**stats))
    except BrokenPipeError:
        # broken pipe happens all the time when piped to less(1), just ignore
        pass


if __name__ == "__main__":
    main()
